image: docker.uib.gmbh/opsi/dev/pybuilder:uib-python-default

stages:
  - build

build:pyinstaller-darwin-x64:
  stage: build
  tags:
    - macos
  script:
    - source $HOME/.poetry/env
    - poetry install
    - poetry run opsi-dev-tool -l info --pyinstaller-poetry-build
    - ./dist/oca-installation-helper --version
    - '[ "$CI_COMMIT_TAG" = "" ] && poetry run opsi-dev-tool -l info --binary-push dist/oca-installation-helper "$CI_JOB_ID"'
    - '[ "$CI_COMMIT_TAG" = "" ] || poetry run opsi-dev-tool -l info --binary-push dist/oca-installation-helper'

build:pyinstaller-linux-x64:
  stage: build
  script:
    - poetry install
    - poetry run opsi-dev-tool -l info --pyinstaller-poetry-build
    - ./dist/oca-installation-helper --version
    - '[ "$CI_COMMIT_TAG" = "" ] && opsi-dev-tool -l info --binary-push dist/oca-installation-helper "$CI_JOB_ID"'
    - '[ "$CI_COMMIT_TAG" = "" ] || opsi-dev-tool -l info --binary-push dist/oca-installation-helper'


build:pyinstaller-windows-x86:
  stage: build
  tags:
    - win10
  script:
    - poetry install
    - poetry run opsi-dev-tool -l debug --pyinstaller-poetry-build
    - poetry run opsi-dev-tool -l info --signserver-sign dist\oca-installation-helper.exe
    # Check if binary is working
    - dist\oca-installation-helper.exe --version
    # Push to binaryindex
    - if (! $CI_COMMIT_TAG) {poetry run opsi-dev-tool -l info --binary-push dist\oca-installation-helper.exe "$CI_JOB_ID"}
    - if ($CI_COMMIT_TAG) {poetry run opsi-dev-tool -l info --binary-push dist\oca-installation-helper.exe}
