[project]
name = "oca-installation-helper"
version = "4.3.8.0"
readme = "README.md"
requires-python = ">=3.13,<3.15"
description = "installer for opsi-client-agent packages"
license = "AGPL-3.0-only"
dependencies = [
	"cryptography>=42.0.0",
	"netifaces~=0.11",
	"pillow>=11.2.1",
	"psutil>=7.0.0",
	"pydantic-core>=2.20",
	"pydantic>=2.9",
	"python-opsi>=4.3,<4.4",
	"rich>=13.9.4",
	"textual~=0.81.0",
	"websocket-client",
	"zeroconf>=0.136.2",
	"pywinpty<3; platform_system == 'Windows'",
]

[project.urls]
Homepage = "https://www.opsi.org"

[[project.authors]]
name = "uib GmbH"
email = "info@uib.de"

[[project.maintainers]]
name = "uib GmbH"
email = "info@uib.de"

[dependency-groups]
dev = [
	"pyinstaller",
	"pytest-asyncio",
	"pytest-cov",
	"pytest",
	"ruff",
	"ty",
	"types-psutil",
	"typing-extensions",
]

[project.scripts]
oca-installation-helper = "ocainstallationhelper.__main__:main"

[tool.ruff]
line-length = 140

[tool.ruff.format]
indent-style = "tab"

[tool.uv]
extra-index-url = ["https://pypi.uib.gmbh/simple"]
index-strategy = "unsafe-best-match"
package = true

[tool.setuptools.packages.find]
include = ["ocainstallationhelper", "ocainstallationhelper.*"]
